config/routes.rb
StartUp::Application.routes.draw do
  root 'products#index'
  resources :products do
    member do
      get 'options'
      get 'variants'
      get 'properties'
      get 'images'
    end
  end
  resources :options
  resources :properties
  resources :variants

end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :values, as: :valuable
  has_many :product_collections, as: :collectable

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_filter :get_property, only: [:edit,:update,:destroy]
  before_filter :set_active_menu

  def set_active_menu
    @active_menu = "products"
    @sub_menu << [options_path, t(:options), ""]
    @sub_menu << [properties_path, t(:properties), "active"]
  end

  def index
    @properties = Property.all
    @property = Property.new
  end
  def create
    @property = Property.new property_params
    @property.save

    redirect_to properties_path
  end
  def edit
    
  end
  def update
    @property.update_attributes property_params
    redirect_to properties_path
  end
  def destroy
    @property.product_collections.each do |product_collection|
      product_collection.destroy
    end
    @property.values.each do |value|
      value.destroy
    end
    @property.destroy
    redirect_to properties_path
  end

  private
    def get_property
      @property = Property.find(params[:id])
    end

    def property_params
      params.require(:property).permit!
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= nested_form_for property, html: {class: 'form'} do |f| %>
  <div id="search-box" class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-sm-5 hidden-xs">
          <hr>
        </div>
        <div class="col-sm-2 text-center">
          <div class="title"><%= action_name == "edit" ? t(:edit_property) : t(:new_property) %></div >
        </div>
        <div class="col-sm-5 hidden-xs">
          <hr>
        </div>
      </div>
    </div>
    <fieldset>
      <div class="col-sm-12">
        <%= f.label t(:name) %><br>
        <%= f.text_field :name %>
      </div>
    </fieldset>
    <div class="col-sm-4 hidden-xs">
      <hr>
    </div>
    <div class="col-sm-4 text-center">
      <div class="title button"><%= f.submit action_name == "edit" ? t(:edit) : t(:create) %></div >
    </div>
    <div class="col-sm-4 hidden-xs">
      <hr>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<%= render partial: "form", locals: {property: @property}%>

app/views/properties/index.html.erb
<%= render partial: "form", locals: {property: @property}%>
<div class="row product-index">
  <div class="col-xs-8">
    <b><%= t(:name).upcase %></b>
  </div>
  <div class="col-xs-4">
    <b><%= t(:actions).upcase %></b>
  </div>
  <div class="col-sm-12">
    <hr>
  </div>
  <% @properties.each do |property| %>
    <div class="col-xs-8">
      <%= property.name %>
    </div>
    <div class="col-xs-4">
      <%= link_to(edit_property_path(property)) do %>
        <i class='fa fa-pencil-square-o'></i>
      <% end %>
      <%= link_to( property, :confirm => 'Are you sure?', :method => :delete ) do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </div>
    <div class="col-xs-12">
      <hr>
    </div>
  <% end %>
</dvi>