config/routes.rb
StartUp::Application.routes.draw do
  root 'products#index'
  resources :products do
    member do
      get 'options'
      get 'variants'
      get 'properties'
      get 'images'
    end
  end
  resources :options
  resources :properties
  resources :variants

end

app/models/option.rb
class Option < ActiveRecord::Base
  has_many :values, as: :valuable
  has_many :product_collections, as: :collectable
  has_many :option_choices

  belongs_to :product

  accepts_nested_attributes_for :option_choices, :allow_destroy => true

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_filter :get_option, only: [:edit,:update,:destroy]
  before_filter :set_active_menu

  def set_active_menu
    @active_menu = "products"
    @sub_menu << [options_path, t(:options), "active"]
    @sub_menu << [properties_path, t(:properties), ""]
  end

  def index
    @options = Option.all
    @option = Option.new
  end

  def create
    @option = Option.new option_params
    @option.save

    redirect_to options_path
  end

  def edit
    @foot_links << [options_path(product_id: @option.product_id),"BACK TO OPTIONS","grey"]
  end

  def update
    @option.update_attributes option_params
    redirect_to options_path
  end

  def destroy

    @option.product_collections.each do |product_collection|
      product_collection.destroy
    end

    @option.values.each do |value|
      value.destroy
    end

    @option.option_choices.each do |option_choice|
      option_choice.destroy
    end

    @option.destroy
    redirect_to options_path
  end

  private

    def get_option
      @option = Option.find(params[:id])
    end

    def option_params
      params.require(:option).permit!
    end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_choice_form.html.erb
<div class="col-xs-12">
  <%= form.label t(:choices) %><br>
</div>
<div class="col-xs-12">
  
  <%= form.fields_for :option_choices do |o| %>
  <div class="row">
      <div class="col-xs-10">
        <%= o.text_field :value %>
      </div>
      <div class="col-xs-2">
        <%= o.link_to_remove do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </div>
  </div>    
  <% end %>  
  
  <%= form.link_to_add t("add_choice"), :option_choices, class: "button title" %>
</div>

app/views/options/_form.html.erb
<%= nested_form_for option, html: {class: 'form'} do |f| %>
  <div id="search-box" class="row">
    <div class="col-xs-12">
      <div class="row">
        <div class="col-sm-5 hidden-xs">
          <hr>
        </div>
        <div class="col-sm-2 text-center">
          <div class="title"><%= action_name == "edit" ? t(:edit_option) : t(:new_option) %></div >
        </div>
        <div class="col-sm-5 hidden-xs">
          <hr>
        </div>
      </div>
    </div>
    <fieldset>
      <div class="col-sm-12">
        <%= f.label t(:name) %><br>
        <%= f.text_field :name %>
      </div>
      <%= render partial: "choice_form", locals: {form: f} if action_name == "edit" %>
    </fieldset>
    <div class="col-sm-4 hidden-xs">
      <hr>
    </div>
    <div class="col-sm-4 text-center">
      <div class="title button"><%= f.submit action_name == "edit" ? t(:edit) : t(:create) %></div >
    </div>
    <div class="col-sm-4 hidden-xs">
      <hr>
    </div>
  </div>
<% end %>

app/views/options/edit.html.erb
<%= render partial: "form", locals: {option: @option}%>

app/views/options/index.html.erb
<%= render partial: "form", locals: {option: @option}%>
<div class="row product-index">
  <div class="col-xs-8">
    <b><%= t(:name).upcase %></b>
  </div>
  <div class="col-xs-4">
    <b><%= t(:actions).upcase %></b>
  </div>
  <div class="col-sm-12">
    <hr>
  </div>
  <% @options.each do |option| %>
    <div class="col-xs-8">
      <%= option.name %>
    </div>
    <div class="col-xs-4">
      <%= link_to(edit_option_path(option)) do %>
        <i class='fa fa-pencil-square-o'></i>
      <% end %>
      <%= link_to( option, :confirm => 'Are you sure?', :method => :delete ) do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </div>
    <div class="col-xs-12">
      <hr>
    </div>
  <% end %>
</dvi>