config/routes.rb
StartUp::Application.routes.draw do
  root 'products#index'
  resources :products do
    member do
      get 'options'
      get 'variants'
      get 'properties'
      get 'images'
    end
  end
  resources :options
  resources :properties
  resources :variants

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :options
  has_many :variants
  has_many :images, as: :imageable
  has_many :values, as: :originator
  has_many :product_collections
  attr_accessor :option_ids, :property_ids

  accepts_nested_attributes_for :images, :allow_destroy => true
  accepts_nested_attributes_for :values, :allow_destroy => true
  accepts_nested_attributes_for :variants, :allow_destroy => true

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :sku, uniqueness: true
  validates :on_hand, numericality: true
  validates :master_price, numericality: true

  def initialize(attributes={})
    attr_with_defaults = {master_price: 0.00,
                          on_hand: 0,
      }.merge(attributes)
    super(attr_with_defaults)
  end

  def has_variants?
    self.variants.present?
  end

  def option_ids
    product_collections.where(collectable_type: "Option").pluck(:collectable_id)
  end

  def property_ids
    product_collections.where(collectable_type: "Property").pluck(:collectable_id)
  end

  def update_collection(hash = {})
    if hash[:ids].present?
      ids = hash[:ids].map{|x| x.to_i if x.present?}.compact!
      ids.each do |id|
        unless product_collections.find_by_collectable_id_and_collectable_type(id,hash[:type])
          product_collections.create(collectable_id: id, collectable_type: hash[:type])
          # do not create value for product if type is option
          values.create(valuable_id: id, valuable_type: hash[:type]) unless hash[:type] == "Option"
          if variants.present? && hash[:type] == "Option"
            variants.each do |v|
              v.values.create(valuable_id: id, valuable_type: hash[:type])
            end
          end
        end
      end

      #find unused ids
      unused_ids =  product_collections.where(collectable_type: hash[:type]).pluck(:collectable_id) - ids
      
      #destroy them if exist
      if unused_ids.present?
        ProductCollection.where(collectable_id: unused_ids, collectable_type: hash[:type], product_id: self.id).each do |c|
          c.destroy
          Value.remove_value(c.product,c.collectable)
          if variants.present? && hash[:type] == "Option"
            variants.each do |v|
              Value.remove_value(v,c.collectable)
            end
          end
        end
      end

    end   
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :get_product, only: [:show,:edit,:update,:destroy,:options,:variants,:properties,:images]
  before_filter :set_active_menu
  before_filter :set_to_product, only: [:images,:properties]

  def set_active_menu
    @active_menu = "products"
    @sub_menu << [options_path, t(:options), ""]
    @sub_menu << [properties_path, t(:properties), ""]
  end

  def set_to_product
    @head_links << [edit_product_path, @product.name, "button"]
  end

  def index
    @q = Product.search(params[:q])
    @products = @q.result(distinct: true)
    @head_links << [new_product_path, t(:new), "button"]
  end

  def show
    @head_links << [edit_product_path(@product),"EDIT PRODUCT","yellow"]
    @foot_links << [products_path,"BACK TO PRODUCTS","grey"]
  end

  def new
    @product = Product.new
    @foot_links << [products_path,"BACK TO PRODUCTS","grey"]
  end

  def create
    @product = Product.new product_params

    if @product.save
      redirect_to edit_product_path(@product)
    else
      redirect_to new_product_path
    end
  end

  def edit
    @head_links << [variants_product_path(@product), t(:variants),"button"]
    @head_links << [properties_product_path, t(:properties),"button"]
    @head_links << [images_product_path(@product), t(:images),"button"]
  end

  def update
    @product.update_attributes product_params
     
    @product.update_collection({type: "Option", ids: params[:product][:option_ids]})
    @product.update_collection({type: "Property", ids: params[:product][:property_ids]})

    redirect_to edit_product_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def variants
    @variants = @product.variants
    @variant = Variant.new(product_id: @product.id)
    @head_links << [edit_product_path, @product.name, "button"]
  end

  def properties
    
  end

  def images
    
  end

  private
    def disable_form
      @disable_form = true
    end

    def get_product
      @product = Product.find(params[:id])
    end
    def product_params
      params.require(:product).permit!
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if product.new_record? %>
  <%= form_for product, html: {class: 'form'} do |f| %>
    <div id="search-box" class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-sm-5 hidden-xs">
            <hr>
          </div>
          <div class="col-sm-2 text-center">
            <div class="title"><%= t(:new_product)  %></div >
          </div>
          <div class="col-sm-5 hidden-xs">
            <hr>
          </div>
        </div>
      </div>
      <fieldset>
        <div class="col-sm-9">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label t(:name) %><br>
              <%= f.text_field :name %>
            </div>
            <div class="col-sm-12">
              <%= f.label t(:sku) %><br>
              <%= f.text_field :sku %>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="row">
            <div class="col-sm-12">
              <%= f.label t(:master_price) %><br>
              <%= f.text_field :master_price %>
            </div>
            <div class="col-sm-12">
              <%= f.label t(:on_hand) %><br>
              <%= f.text_field :on_hand %>
            </div>
          </div>
        </div>
      </fieldset>
      <div class="col-sm-4 hidden-xs">
        <hr>
      </div>
      <div class="col-sm-4 text-center">
        <div class="title button"><%= f.submit t(:create) %></div >
      </div>
      <div class="col-sm-4 hidden-xs">
        <hr>
      </div>
    </div>
  <% end %>
<% else %>
  <%= form_for product, html: {class: 'form'} do |f| %>
    <div id="search-box" class="row">
      <div class="col-xs-12">
        <div class="row">
          <div class="col-sm-5 hidden-xs">
            <hr>
          </div>
          <div class="col-sm-2 text-center">
            <div class="title"><%= t(:edit_product)  %></div >
          </div>
          <div class="col-sm-5 hidden-xs">
            <hr>
          </div>
        </div>
      </div>
      <fieldset>
        <% case action_name %>
          <% when "edit" %>
            <%= render partial: "products/full_fields",locals: {f: f} %>
          <% when "options" %>
            <%= render partial: "products/values_fields",locals: {f: f} %>
          <% when "properties" %>
            <%= render partial: "products/values_fields",locals: {f: f} %>
        <% end %>
      </fieldset>
      <div class="col-sm-4 hidden-xs">
        <hr>
      </div>
      <div class="col-sm-4 text-center">
        <div class="title button"><%= f.submit t(:edit) %></div >
      </div>
      <div class="col-sm-4 hidden-xs">
        <hr>
      </div>
    </div>
  <% end %>
<% end %>

app/views/products/_full_fields.html.erb
<div class="col-sm-9">
  <div class="row">
    <div class="col-sm-12">
      <%= f.label t(:name) %><br>
      <%= f.text_field :name %>
    </div>
    <div class="col-sm-12">
      <%= f.label t(:sku) %><br>
      <%= f.text_field :sku %>
    </div>
    <div class="col-sm-12">
      <%= f.label t(:description) %><br>
      <%= f.text_area :description %>
    </div>
  </div>
</div>
<div class="col-sm-3">
  <div class="row">
    <div class="col-sm-12">
      <%= f.label t(:master_price) %><br>
      <%= f.text_field :master_price %>
    </div>
    <div class="col-sm-12">
      <%= f.label t(:on_hand) %><br>
      <%= f.text_field :on_hand %>
    </div>
  </div>
</div>
<div class="col-sm-12">
  <%= f.label t(:options) %><br>
  <%= f.select :option_ids,
    Option.all.map { |option| [option.name, option.id] },
    { include_blank: true },
    { class: 'chosen-select', multiple: true }
  %>
</div>
<div class="col-sm-12">
  <%= f.label t(:properties) %><br>
  <%= f.select :property_ids,
    Property.all.map { |property| [property.name, property.id] },
    { include_blank: true },
    { class: 'chosen-select', multiple: true }
  %>
</div>

app/views/products/_search.html.erb
<%= search_form_for @q, class: "form" do |f| %>
<div id="search-box" class="row">
  <div class="col-sm-5 hidden-xs">
    <hr>
  </div>
  <div class="col-sm-2 text-center">
    <div class="title"><%= t(:search) %></div >
  </div>
  <div class="col-sm-5 hidden-xs">
    <hr>
  </div>
  <fieldset>
    <div class="col-sm-12">
      <%= f.label :name_cont, "Name" %><br>
      <%= f.text_field :name_cont %>
    </div>
  </fieldset>
  <div class="col-sm-4 hidden-xs">
    <hr>
  </div>
  <div class="col-sm-4 text-center">
    <div class="title button"><%= f.submit t(:search) %></div >
  </div>
  <div class="col-sm-4 hidden-xs">
    <hr>
  </div>
</div>
<% end %>

app/views/products/_values_fields.html.erb
<%= f.fields_for :values do |value| %>
  <% if value.object.valuable_type == action_name.titleize.singularize %>
    <div class="col-xs-12">
      <%= value.label "#{value.object.valuable_name.titleize }"%></br>
      <%= value.text_field :value %>
    </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<%= render partial: "form.html.erb", locals: {product: @product} %>

app/views/products/images.html.erb
<%= render partial: "shared/image_form", locals: {resource: @product} %>

app/views/products/index.html.erb
<%= render "products/search" %>
<div class="row product-index">
  <div class="col-xs-8">
    <b><%= t(:name).upcase %></b>
  </div>
  <div class="col-xs-4">
    <b><%= t(:actions).upcase %></b>
  </div>
  <div class="col-sm-12">
    <hr>
  </div>
  <% @products.each do |product| %>
    <div class="col-xs-8">
      <%= product.name %>
    </div>
    <div class="col-xs-4">
      <%= link_to(edit_product_path(product)) do %>
        <i class='fa fa-pencil-square-o'></i>
      <% end %>
      <%= link_to(edit_product_path(product)) do %>
        <i class="fa fa-files-o"></i>
      <% end %>
      <%= link_to( product, :confirm => 'Are you sure?', :method => :delete ) do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </div>
    <div class="col-xs-12">
      <hr>
    </div>
  <% end %>
</dvi>

app/views/products/new.html.erb
<%= render partial: "form.html.erb", locals: {product: @product} %>
<% content_for :foot do %>
  <div class="col-xs-12 foot">
      <ul class="foot">
        <div class="pull-left">
          <li class="grey"><%= link_to "BACK", products_path %></li>
      </div>
    </ul>
  </div>
<% end %>

app/views/products/properties.html.erb
<%= render partial: "products/form", locals: {product: @product} %>

app/views/products/show.html.erb
<h1><%= @product.label %></h1>
<%= render partial: "form.html.erb", locals: {product: @product} %>

app/views/products/variants.html.erb
<%= render partial: "/variants/form", locals: {variant: @variant} %>
<div class="row product-index">
  <div class="col-xs-8">
    <b><%= t(:name).upcase %></b>
  </div>
  <div class="col-xs-4">
    <b><%= t(:actions).upcase %></b>
  </div>
  <div class="col-sm-12">
    <hr>
  </div>
  <% @variants.each do |variant| %>
    <div class="col-xs-8">
      <%= variant.product.name %> <%= variant.name %>
    </div>
    <div class="col-xs-4">
      <%= link_to(edit_variant_path(variant)) do %>
        <i class='fa fa-pencil-square-o'></i>
      <% end %>
      <%= link_to(edit_variant_path(variant)) do %>
        <i class="fa fa-files-o"></i>
      <% end %>
      <%= link_to( variant, :confirm => 'Are you sure?', :method => :delete ) do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </div>
    <div class="col-xs-12">
      <hr>
    </div>
  <% end %>
</dvi>